project_id = "zovakngafdwzbqhwvssf"

[functions.ai-writing]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.parse-pdf]
verify_jwt = false

[functions.graphics-admin]
verify_jwt = false

[functions.generate-goodnotes-pdf]
verify_jwt = false

[functions.share-blog]
verify_jwt = false

[functions.sync-blog-posts]
verify_jwt = false

[functions.share-book]
verify_jwt = false

[functions.share-sermon]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.check-purchase]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.videos-admin]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.create-invite]
verify_jwt = false

[functions.redeem-invite]
verify_jwt = false

[functions.share-invite]
verify_jwt = false

[functions.request-login-code]
verify_jwt = false

[functions.verify-login-code]
verify_jwt = false

[functions.redeem-access-code]
verify_jwt = false

[functions.create-donation-checkout]
verify_jwt = false
