project_id = "zovakngafdwzbqhwvssf"

[functions.ai-writing]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.parse-pdf]
verify_jwt = false

[functions.graphics-admin]
verify_jwt = false

[functions.generate-goodnotes-pdf]
verify_jwt = false

[functions.blogshare]
verify_jwt = false
